pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
   post {
        success {
            // Actions to perform if the build is successful
            echo 'Java program executed successfully!'
        }
        failure {
            // Actions to perform if the build fails
            echo 'Failed to execute Java program.'
        }
    }
}
